<a href="https://colab.research.google.com/github/bosunKwak/Brno_Machine-Learning/blob/main/Brno_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(2+3)
print(3-2)
print(3*2)

5
1
6


In [ ]:
print(7/2)
print(7//2)
print(7%2)

3.5
3
1


In [ ]:
print(7-(2+3))
print(3**2)
print(3*3)
print(16**0.5)
print((10**3+10**2)/2)

2
9
9
4.0
550.0


In [ ]:
print(5+3)
print(4*40)
print(6/7)

8
160
0.8571428571428571


In [ ]:
income_alice = 1000
income_bob = 100
print(income_alice, income_bob)

1000 100


In [ ]:
(income_alice+income_bob)/2

550.0

In [ ]:
def average(a,b):
  return (a+b)/2
average(income_alice,income_bob)

550.0

In [ ]:
def sum(a,b):
  return (a+b)

In [ ]:
sum("I"," am")

'I am'

In [ ]:
average(income_alice+2,7)

504.5

In [ ]:
def interpolate(a,b,t):
  dist = (b-a)*t
  return dist+a

print(interpolate(0,10,0.7))
print(interpolate(-5,5,0.25))

7.0
-2.5


In [ ]:
def interp2(a,b,t):
  return a*(1-t) + b*t

print(interp2(0,10,0.7))
print(interp2(-5,5,0.25))

7.0
-2.5


In [ ]:
def tax(income):
  if income<10000:
    return 0
  else:
    return 0.1 * income
    
print(tax(9000))
print(tax(11000))

0
1100.0


In [ ]:
def tax(income):
  if income<10000:
    return 0
  elif income>50000:
    return 0.2*income
  else:
    return 1000

print(tax(9000))
print(tax(11000))
print(tax(income_alice))
print(tax(58000))

0
1000
0
11600.0


In [ ]:
abs((0.1+0.2)-0.3)<1e-10

True

In [ ]:
my_list = [1,4,9,16,25,36]

In [ ]:
print(my_list[0])
print(my_list[-1])
print(my_list[-2:])
print(my_list[2:3])
print(my_list[5-2:])

1
36
[25, 36]
[9]
[16, 25, 36]


In [ ]:
for x in my_list:
  print(x,x**2)

1 1
4 16
9 81
16 256
25 625
36 1296


In [ ]:
running_sum = 0
for x in my_list:
  running_sum += x
print(running_sum)

91


In [ ]:
my_list2 = [1,4,9,16]
def averare(my_list):
  running_sum = 0
  for x in my_list:
    running_sum += x
  return running_sum/len(my_list)

print(averare(my_list2))

4
7.5


In [ ]:
def print_fibonacci(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return print_fibonacci(n-1)+print_fibonacci(n-2)
  
print(print_fibonacci(6))

8


In [ ]:
def print_fibonacci2(n):
  arr = [None for _ in range(n)]
  for i in range(n):
    arr[i] = print_fibonacci(i)
  return arr
print_fibonacci2(7)

[0, 1, 1, 2, 3, 5, 8]

In [ ]:
def print_fib3(n):
  if n<= 0:
    print("Can't do that")
    return
  elif n==1:
    array = [0]
  else:
    array = [None for _ in range(n)]
    array[0] = 0
    array[1] = 1
    for i in range(n-2):
      array[i+2] = array[i+1] + array[i]
   
  print(f'First {n} Fibonacci numbers are {array}')
 

print_fib3(3)
print_fib3(7)

First 3 Fibonacci numbers are [0, 1, 1]
First 7 Fibonacci numbers are [0, 1, 1, 2, 3, 5, 8]


In [ ]:
my_tuple = (1,2,3)

In [ ]:
print(my_tuple[1])

2


In [ ]:
# error - tuple cannt change
#my_tuple[1] = 42

In [ ]:
kbs_doe = {'age': 24,'income': 0, 'address': 'Seoul'}

In [ ]:
kbs_doe

{'address': 'Seoul', 'age': 24, 'income': 0}

In [ ]:
print(kbs_doe)

{'age': 24, 'income': 0, 'address': 'Seoul'}


In [ ]:
kbs_doe['age']

24

In [ ]:
print(my_list)

[1, 4, 9, 16, 25, 36]


In [ ]:
{x: f'The square is {x**2}.' for x in my_list}

{1: 'The square is 1.',
 4: 'The square is 16.',
 9: 'The square is 81.',
 16: 'The square is 256.',
 25: 'The square is 625.',
 36: 'The square is 1296.'}

In [ ]:
[x**2 for x in my_list if x %2 == 0]

[16, 256, 1296]

In [ ]:
x = [1,2,4]
y = [0,7,-1]

In [ ]:
def dot1(x,y):
  sum = 0
  for i in range(len(x)):
    sum += x[i]*y[i]
  return sum


In [ ]:
def dot2(x,y):
  return sum([a*b for a,b in zip(x,y)])
# https://www.daleseo.com/python-zip/

In [ ]:
print(x,y,'->',dot1(x,y))
print(x,y,'->',dot2(x,y))

[1, 2, 4] [0, 7, -1] -> 10
[1, 2, 4] [0, 7, -1] -> 10


In [ ]:
x_big = list(range(1500))
y_big = list(range(1500))

print('x',len(x_big), x_big[:5],x_big[-5:])

x 1500 [0, 1, 2, 3, 4] [1495, 1496, 1497, 1498, 1499]


In [ ]:
import time
t0 = time.time()
dot1(x_big, y_big)
t1 = time.time()

print(f'It took {t1-t0} seconds')
print(f'It took {1000.*(t1-t0):.2f} miliseconds')

It took 0.0005633831024169922 seconds
It took 0.56 miliseconds


In [ ]:
dot1 = dot1(x,y)

In [ ]:
dot1

10

In [ ]:
my_list = [1,'hello',[2,3],{1:11,2:22,3:43}]

In [ ]:
my_list[2]

[2, 3]

In [ ]:
import numpy 
vec1 = numpy.asarray([1,2,3])
print(vec1)

[1 2 3]


In [ ]:
import numpy as np
vec2 = np.asarray([1,2,0,3])
print(vec2)

[1 2 0 3]


In [ ]:
vec1 = np.asarray(x)
vec2 = np.asarray(y)
print(vec1,vec2)

[1 2 4] [ 0  7 -1]


In [ ]:
vec1 +1

array([2, 3, 5])

In [ ]:
vec1 + vec2

array([1, 9, 3])

In [ ]:
np.sum(vec1)

7

In [ ]:
def dot3(x,y):
  return np.sum(x*y)
dot3(vec1,vec2)

10

In [ ]:
t0 = time.time()
for _ in range(100):
  dot3(np.asarray(x_big), np.asarray(y_big))

t1 = time.time()

print(f'It took {1000.*(t1-t0):.2f} miliseconds')

It took 36.16 miliseconds
